name: Janoub Price Monitor (Custom-Sync)

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim  # نفس البيئة اللي شفرنا فيها

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Run Obfuscated Monitor
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
          SCRAPING_MODE: ${{ secrets.SCRAPING_MODE }}
        run: python main.py
